<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\City;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = new \DateTime();
        $data = [
            // aceh
            [ 'name' => "Kota Banda Aceh", 'state_id' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Sabang", 'state_id' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Lhokseumawe", 'state_id' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Langsa", 'state_id' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Subulussalam", 'state_id' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Aceh Selatan", 'state_id' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Aceh Tenggara", 'state_id' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Aceh Timur", 'state_id' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Aceh Tengah", 'state_id' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Aceh Barat", 'state_id' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Aceh Besar", 'state_id' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Pidie", 'state_id' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Aceh Utara", 'state_id' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Simeulue", 'state_id' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Aceh Singkil", 'state_id' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bireun", 'state_id' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Aceh Barat Daya", 'state_id' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Gayo Lues", 'state_id' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Aceh Jaya", 'state_id' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Nagan Raya", 'state_id' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Aceh Tamiang", 'state_id' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bener Meriah", 'state_id' => 1, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Pidie Jaya", 'state_id' => 1, 'created_at' => $now, 'updated_at' => $now ],
            // sumatera utara
            [ 'name' => "Kota Medan", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Pematang Siantar", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Sibolga", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Tanjung Balai", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Binjai", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Tebing Tinggi", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Padang Sidempuan", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Gunung Sitoli", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Serdang Bedagai", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Samosir", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Humbang Hasundutan", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Pakpak Bharat", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Nias Selatan", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Mandailing Natal", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Toba Samosir", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Dairi", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Labuhan Batu", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Asahan", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Simalungun", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Deli Serdang", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Karo", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Langkat", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Nias", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Tapanuli Selatan", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Tapanuli Utara", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Tapanuli Tengah", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Batu Bara", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Padang Lawas Utara", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Padang Lawas", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Labuhanbatu Selatan", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Labuhanbatu Utara", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Nias Utara", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Nias Barat", 'state_id' => 34, 'created_at' => $now, 'updated_at' => $now ],
            // sumatera barat
            [ 'name' => "Kota Padang", 'state_id' => 32, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Solok", 'state_id' => 32, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Sawhlunto", 'state_id' => 32, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Padang Panjang", 'state_id' => 32, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Bukittinggi", 'state_id' => 32, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Payakumbuh", 'state_id' => 32, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Pariaman", 'state_id' => 32, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Pasaman Barat", 'state_id' => 32, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Solok Selatan", 'state_id' => 32, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Dharmasraya", 'state_id' => 32, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kepulauan Mentawai", 'state_id' => 32, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Pasaman", 'state_id' => 32, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Lima Puluh Kota", 'state_id' => 32, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Agam", 'state_id' => 32, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Padang Pariaman", 'state_id' => 32, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Tanah Datar", 'state_id' => 32, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sijunjung", 'state_id' => 32, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Solok", 'state_id' => 32, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Pesisir Selatan", 'state_id' => 32, 'created_at' => $now, 'updated_at' => $now ],
            // riau
            [ 'name' => "Kota Pekan Baru", 'state_id' => 26, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Dumai", 'state_id' => 26, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kepulauan Meranti", 'state_id' => 26, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kuantan Singingi", 'state_id' => 26, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Siak", 'state_id' => 26, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Rokan Hilir", 'state_id' => 26, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Rokan Hulu", 'state_id' => 26, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Pelalawan", 'state_id' => 26, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Indragiri Hilir", 'state_id' => 26, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bengkalis", 'state_id' => 26, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Indragiri Hulu", 'state_id' => 26, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kampar", 'state_id' => 26, 'created_at' => $now, 'updated_at' => $now ],
            // jambi
            [ 'name' => "Kota Jambi", 'state_id' => 8, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Sungai Penuh", 'state_id' => 8, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Tebo", 'state_id' => 8, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bungo", 'state_id' => 8, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Tanjung Jabung Timur", 'state_id' => 8, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Tanjung Jabung Barat", 'state_id' => 8, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Muaro Jambi", 'state_id' => 8, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Batanghari", 'state_id' => 8, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sarolangun", 'state_id' => 8, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Merangin", 'state_id' => 8, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kerinci", 'state_id' => 8, 'created_at' => $now, 'updated_at' => $now ],
            // sumatera selatan
            [ 'name' => "Kota Palembang", 'state_id' => 33, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Pagar Alam", 'state_id' => 33, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Lubuk Linggau", 'state_id' => 33, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Prabumulih", 'state_id' => 33, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Musi Rawas Utara", 'state_id' => 33, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Penukal Abab Lematang Ilir", 'state_id' => 33, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Empat Lawang", 'state_id' => 33, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Ogan Ilir", 'state_id' => 33, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Ogan Komering Ulu Selatan", 'state_id' => 33, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Ogan Komering Ulu Timur", 'state_id' => 33, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Banyuasin", 'state_id' => 33, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Musi Banyuasin", 'state_id' => 33, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Musi Rawas", 'state_id' => 33, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Lahat", 'state_id' => 33, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Muara Enim", 'state_id' => 33, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Ogan Komering Ilir", 'state_id' => 33, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Ogan Komering Ulu", 'state_id' => 33, 'created_at' => $now, 'updated_at' => $now ],
            // bengkulu
            [ 'name' => "Kota Bengkulu", 'state_id' => 4, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bengkulu Tengah", 'state_id' => 4, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kepahiang", 'state_id' => 4, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Lebong", 'state_id' => 4, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Muko Muko", 'state_id' => 4, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Seluma", 'state_id' => 4, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kaur", 'state_id' => 4, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bengkulu Utara", 'state_id' => 4, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Rejang Lebong", 'state_id' => 4, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bengkulu Selatan", 'state_id' => 4, 'created_at' => $now, 'updated_at' => $now ],
            // lampung
            [ 'name' => "Kota Bandar Lampung", 'state_id' => 19, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Metro", 'state_id' => 19, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Pesisir Barat", 'state_id' => 19, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Tulangbawang Barat", 'state_id' => 19, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Mesuji", 'state_id' => 19, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Pringsewu", 'state_id' => 19, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Pesawaran", 'state_id' => 19, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Way Kanan", 'state_id' => 19, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Lampung Timur", 'state_id' => 19, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Tanggamus", 'state_id' => 19, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Tulang Bawang", 'state_id' => 19, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Lampung Barat", 'state_id' => 19, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Lampung Utara", 'state_id' => 19, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Lampung Tengah", 'state_id' => 19, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Lampung Selatan", 'state_id' => 19, 'created_at' => $now, 'updated_at' => $now ],
            // Kepulauan Bangka Belitung
            [ 'name' => "Kota Pangkal Pinang", 'state_id' => 17, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Belitung Timur", 'state_id' => 17, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bangka Barat", 'state_id' => 17, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bangka Tengah", 'state_id' => 17, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bangka Selatan", 'state_id' => 17, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Belitung", 'state_id' => 17, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bangka", 'state_id' => 17, 'created_at' => $now, 'updated_at' => $now ],
            // Kepulauan Riau
            [ 'name' => "Kota Batam", 'state_id' => 18, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Tanjung Pinang", 'state_id' => 18, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kepulauan Anambas", 'state_id' => 18, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Lingga", 'state_id' => 18, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Natuna", 'state_id' => 18, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Karimun", 'state_id' => 18, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bintan", 'state_id' => 18, 'created_at' => $now, 'updated_at' => $now ],
            // DKI Jakarta
            [ 'name' => "Kota Jakarta Timur", 'state_id' => 6, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Jakarta Selatan", 'state_id' => 6, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Jakarta Barat", 'state_id' => 6, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Jakarta Utara", 'state_id' => 6, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Jakarta Pusat", 'state_id' => 6, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kepulauan Seribu", 'state_id' => 6, 'created_at' => $now, 'updated_at' => $now ],
            // Jawa Barat
            [ 'name' => "Kota Bandung", 'state_id' => 9, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Banjar", 'state_id' => 9, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Tasikmalaya", 'state_id' => 9, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Cimahi", 'state_id' => 9, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Depok", 'state_id' => 9, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Bekasi", 'state_id' => 9, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Cirebon", 'state_id' => 9, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Sukabumi", 'state_id' => 9, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Bogor", 'state_id' => 9, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Pangandaran", 'state_id' => 9, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bandung Barat", 'state_id' => 9, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bekasi", 'state_id' => 9, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Karawang", 'state_id' => 9, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Purwakarta", 'state_id' => 9, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Subang", 'state_id' => 9, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Indramayu", 'state_id' => 9, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sumedang", 'state_id' => 9, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Majalengka", 'state_id' => 9, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Cirebon", 'state_id' => 9, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kuningan", 'state_id' => 9, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Ciamis", 'state_id' => 9, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Tasikmalaya", 'state_id' => 9, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Garut", 'state_id' => 9, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bandung", 'state_id' => 9, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Cianjur", 'state_id' => 9, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sukabumi", 'state_id' => 9, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bogor", 'state_id' => 9, 'created_at' => $now, 'updated_at' => $now ],
            // Jawa Tengah
            [ 'name' => "Kota Semarang", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Tegal", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Pekalongan", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Salatiga", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Surakarta", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Magelang", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Brebes", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Tegal", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Pemalang", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Pekalongan", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Batang", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kendal", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Temanggung", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Semarang", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Demak", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Jepara", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kudus", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Pati", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Rembang", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Blora", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Grobogan", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sragen", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Karanganyar", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Wonogiri", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sukoharjo", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Klaten", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Boyolali", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Magelang", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Wonosobo", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Purworejo", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kebumen", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Banjarnegara", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Purbalingga", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Banyumas", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Cilacap", 'state_id' => 10, 'created_at' => $now, 'updated_at' => $now ],
            // DI Yogyakarta
            [ 'name' => "Kota Yogyakarta", 'state_id' => 5, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sleman", 'state_id' => 5, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Gunung Kidul", 'state_id' => 5, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bantul", 'state_id' => 5, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kulon Progo", 'state_id' => 5, 'created_at' => $now, 'updated_at' => $now ],
            // Jawa Timur
            [ 'name' => "Kota Surabaya", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Batu", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Madiun", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Mojokerto", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Pasuruan", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Probolinggo", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Malang", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Blitar", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Kediri", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sumenep", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Pamekasan", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sampang", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bangkalan", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Gresik", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Lamongan", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Tuban", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bojonegoro", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Ngawi", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Magetan", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Madiun", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Nganjuk", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Jombang", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Mojokerto", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sidoarjo", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Pasuruan", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Probolinggo", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Situbondo", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bondowoso", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Banyuwangi", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Jember", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Lumajang", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Malang", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kediri", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Blitar", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Tulungagung", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Trenggalek", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Ponorogo", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Pacitan", 'state_id' => 11, 'created_at' => $now, 'updated_at' => $now ],
            // Banten
            [ 'name' => "Kota Serang", 'state_id' => 3, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Cilegon", 'state_id' => 3, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Tangerang", 'state_id' => 3, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Tangerang Selatan", 'state_id' => 3, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Serang", 'state_id' => 3, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Tangerang", 'state_id' => 3, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Lebak", 'state_id' => 3, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Pandeglang", 'state_id' => 3, 'created_at' => $now, 'updated_at' => $now ],
            // Bali
            [ 'name' => "Kota Denpasar", 'state_id' => 2, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Buleleng", 'state_id' => 2, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Karangasem", 'state_id' => 2, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bangli", 'state_id' => 2, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Klungkung", 'state_id' => 2, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Gianyar", 'state_id' => 2, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Badung", 'state_id' => 2, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Tabanan", 'state_id' => 2, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Jembrana", 'state_id' => 2, 'created_at' => $now, 'updated_at' => $now ],
            // Nusa Tenggara Barat
            [ 'name' => "Kota Mataram", 'state_id' => 22, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Bima", 'state_id' => 22, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Lombok Utara", 'state_id' => 22, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sumbawa Barat", 'state_id' => 22, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bima", 'state_id' => 22, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Dompu", 'state_id' => 22, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sumbawa", 'state_id' => 22, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Lombok Timur", 'state_id' => 22, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Lombok Tengah", 'state_id' => 22, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Lombok Barat", 'state_id' => 22, 'created_at' => $now, 'updated_at' => $now ],
            // Nusa Tenggara Timur
            [ 'name' => "Kota Kupang", 'state_id' => 23, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Malaka", 'state_id' => 23, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sabu Raijua", 'state_id' => 23, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Manggarai Timur", 'state_id' => 23, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sumba Barat Daya", 'state_id' => 23, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sumba Tengah", 'state_id' => 23, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Nagekeo", 'state_id' => 23, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Manggarai Barat", 'state_id' => 23, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Rote Ndao", 'state_id' => 23, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Lembata", 'state_id' => 23, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sumba Barat", 'state_id' => 23, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sumba Timur", 'state_id' => 23, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Manggarai", 'state_id' => 23, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Ngada", 'state_id' => 23, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Ende", 'state_id' => 23, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sikka", 'state_id' => 23, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Flores Timur", 'state_id' => 23, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Alor", 'state_id' => 23, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Belu", 'state_id' => 23, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Timor Tengah Utara", 'state_id' => 23, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Timor Tengah Selatan", 'state_id' => 23, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kupang", 'state_id' => 23, 'created_at' => $now, 'updated_at' => $now ],
            // Kalimantan Barat
            [ 'name' => "Kota Pontianak", 'state_id' => 12, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Singkawang", 'state_id' => 12, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kubu Raya", 'state_id' => 12, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kayong Utara", 'state_id' => 12, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sekadau", 'state_id' => 12, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Melawi", 'state_id' => 12, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Landak", 'state_id' => 12, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bengkayang", 'state_id' => 12, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kapuas Hulu", 'state_id' => 12, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sintang", 'state_id' => 12, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Ketapang", 'state_id' => 12, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sanggau", 'state_id' => 12, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Mempawah", 'state_id' => 12, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sambas", 'state_id' => 12, 'created_at' => $now, 'updated_at' => $now ],
            // Kalimantan Tengah
            [ 'name' => "Kota Palangkaraya", 'state_id' => 14, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Barito Timur", 'state_id' => 14, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Murung Raya", 'state_id' => 14, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Pulang Pisau", 'state_id' => 14, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Gunung Mas", 'state_id' => 14, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Lamandau", 'state_id' => 14, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sukamara", 'state_id' => 14, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Seruyan", 'state_id' => 14, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Katingan", 'state_id' => 14, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Barito Utara", 'state_id' => 14, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Barito Selatan", 'state_id' => 14, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kapuas", 'state_id' => 14, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kotawaringin Timur", 'state_id' => 14, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kotawaringin Barat", 'state_id' => 14, 'created_at' => $now, 'updated_at' => $now ],
            // Kalimantan Selatan
            [ 'name' => "Kota Banjarmasin", 'state_id' => 13, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Banjarbaru", 'state_id' => 13, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Balangan", 'state_id' => 13, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Tanah Bambu", 'state_id' => 13, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Tabalong", 'state_id' => 13, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Hulu Sungai Utara", 'state_id' => 13, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Hulu Sungai Tengah", 'state_id' => 13, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Hulu Sungai Selatan", 'state_id' => 13, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Tapin", 'state_id' => 13, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Barito Kuala", 'state_id' => 13, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Banjar", 'state_id' => 13, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kotabaru", 'state_id' => 13, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Tanah Laut", 'state_id' => 13, 'created_at' => $now, 'updated_at' => $now ],
            // Kalimantan Timur
            [ 'name' => "Kota Samarinda", 'state_id' => 15, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Bontang", 'state_id' => 15, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Balikpapan", 'state_id' => 15, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Mahakam Ulu", 'state_id' => 15, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Penajam Paser Utara", 'state_id' => 15, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kutai Timur", 'state_id' => 15, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kutai Barat", 'state_id' => 15, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Berau", 'state_id' => 15, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kutai Kertanegara", 'state_id' => 15, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Paser", 'state_id' => 15, 'created_at' => $now, 'updated_at' => $now ],
            // Kalimantan Utara
            [ 'name' => "Kota Tarakan", 'state_id' => 16, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Tana Tidung", 'state_id' => 16, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Nunukan", 'state_id' => 16, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Malinau", 'state_id' => 16, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bulungan", 'state_id' => 16, 'created_at' => $now, 'updated_at' => $now ],
            // Sulawesi Utara
            [ 'name' => "Kota Manado", 'state_id' => 31, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Tomohon", 'state_id' => 31, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Bitung", 'state_id' => 31, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Kotamobagu", 'state_id' => 31, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bolaang Mangondow Selatan", 'state_id' => 31, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bolaang Mangondow Timur", 'state_id' => 31, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kepulauan Siau Tagulandang Biaro", 'state_id' => 31, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bolaang Mangondow Utara", 'state_id' => 31, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Minahasa Tenggara", 'state_id' => 31, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Minahasa Utara", 'state_id' => 31, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Minahasa Selatan", 'state_id' => 31, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kepulauan Talaud", 'state_id' => 31, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kepulauan Sangihe", 'state_id' => 31, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Minahasa", 'state_id' => 31, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bolaang Mangondow", 'state_id' => 31, 'created_at' => $now, 'updated_at' => $now ],
            // Sulawesi Tengah
            [ 'name' => "Kota Palu", 'state_id' => 29, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Morowali Utara", 'state_id' => 29, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Banggai Laut", 'state_id' => 29, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sigi", 'state_id' => 29, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Tojo Una-Una", 'state_id' => 29, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Parigi Moutong", 'state_id' => 29, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Banggai Kepulauan", 'state_id' => 29, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Morowali", 'state_id' => 29, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Buol", 'state_id' => 29, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Toli-Toli", 'state_id' => 29, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Donggala", 'state_id' => 29, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Poso", 'state_id' => 29, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Banggai", 'state_id' => 29, 'created_at' => $now, 'updated_at' => $now ],
            // Sulawesi Selatan
            [ 'name' => "Kota Makasar", 'state_id' => 28, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Palopo", 'state_id' => 28, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Pare Pare", 'state_id' => 28, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Toraja Utara", 'state_id' => 28, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Luwu Timur", 'state_id' => 28, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Luwu Utara", 'state_id' => 28, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Tana Toraja", 'state_id' => 28, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Luwu", 'state_id' => 28, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Enrekang", 'state_id' => 28, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Pinrang", 'state_id' => 28, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sidenreng Rappang", 'state_id' => 28, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Wajo", 'state_id' => 28, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Soppeng", 'state_id' => 28, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Barru", 'state_id' => 28, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Pangkajene Kepulauan", 'state_id' => 28, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Maros", 'state_id' => 28, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bone", 'state_id' => 28, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sinjai", 'state_id' => 28, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Gowa", 'state_id' => 28, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Takalar", 'state_id' => 28, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Jeneponto", 'state_id' => 28, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bantaeng", 'state_id' => 28, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bulukumba", 'state_id' => 28, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kepulauan Selayar", 'state_id' => 28, 'created_at' => $now, 'updated_at' => $now ],
            // Sulawesi Tenggara
            [ 'name' => "Kota Kendari", 'state_id' => 30, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Bau Bau", 'state_id' => 30, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Buton Selatan", 'state_id' => 30, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Buton Tengah", 'state_id' => 30, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Muna Barat", 'state_id' => 30, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Konawe Kepulauan", 'state_id' => 30, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kolaka Timur", 'state_id' => 30, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Buton Utara", 'state_id' => 30, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Konawe Utara", 'state_id' => 30, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kolaka Utara", 'state_id' => 30, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Wakatobi", 'state_id' => 30, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bombana", 'state_id' => 30, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Konawe Selatan", 'state_id' => 30, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Buton", 'state_id' => 30, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Muna", 'state_id' => 30, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Konawe", 'state_id' => 30, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kolaka", 'state_id' => 30, 'created_at' => $now, 'updated_at' => $now ],
            // Gorontalo
            [ 'name' => "Kota Gorontalo", 'state_id' => 7, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Pohuwato", 'state_id' => 7, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Bone Bolango", 'state_id' => 7, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Boalemo", 'state_id' => 7, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Gorontalo", 'state_id' => 7, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Gorontalo Utara", 'state_id' => 7, 'created_at' => $now, 'updated_at' => $now ],
            // Sulawesi Barat
            [ 'name' => "Kab. Majene", 'state_id' => 27, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Polowali Mandar", 'state_id' => 27, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Mamasa", 'state_id' => 27, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Mamuju", 'state_id' => 27, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Mamuju Utara", 'state_id' => 27, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Mamuju Tengah", 'state_id' => 27, 'created_at' => $now, 'updated_at' => $now ],
            // Maluku
            [ 'name' => "Kota Ambon", 'state_id' => 20, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Tual", 'state_id' => 20, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Buru Selatan", 'state_id' => 20, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Maluku Barat Daya", 'state_id' => 20, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kepulauan Aru", 'state_id' => 20, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Seram Bagian Barat", 'state_id' => 20, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Seram Bagian Timur", 'state_id' => 20, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Buru", 'state_id' => 20, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Maluku Tenggara Barat", 'state_id' => 20, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Maluku Tenggara", 'state_id' => 20, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Maluku Tengah", 'state_id' => 20, 'created_at' => $now, 'updated_at' => $now ],
            // Maluku Utara
            [ 'name' => "Kota Ternate", 'state_id' => 21, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kota Tidore Kepulauan", 'state_id' => 21, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Pulau Taliabu", 'state_id' => 21, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Pulau Morotai", 'state_id' => 21, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Halmahera Timur", 'state_id' => 21, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kepulauan Sula", 'state_id' => 21, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Halmahera Selatan", 'state_id' => 21, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Halmahera Utara", 'state_id' => 21, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Halmahera Tengah", 'state_id' => 21, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Halmahera Barat", 'state_id' => 21, 'created_at' => $now, 'updated_at' => $now ],
            // Papua
            [ 'name' => "Kota Jayapura", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Deiyai", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Intan Jaya", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Dogiyai", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Puncak", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Nduga", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Lanny Jaya", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Yalimo", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Mamberamo Tengah", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Mamberamo Raya", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Supiori", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Asmat", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Mappi", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Boven Digoel", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Waropen", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Tolikara", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Yahukimo", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Pegunungan Bintang", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Keerom", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sarmi", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Mimika", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Paniai", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Puncak Jaya", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Biak Numfor", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kepulauan Yapen", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Nabire", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Jayapura", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Jayawijaya", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Merauke", 'state_id' => 24, 'created_at' => $now, 'updated_at' => $now ],
            // Papua Barat
            [ 'name' => "Kota Sorong", 'state_id' => 25, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Pegunungan Arfak", 'state_id' => 25, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Manokwari Selatan", 'state_id' => 25, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Maybrat", 'state_id' => 25, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Tambrauw", 'state_id' => 25, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Kaimana", 'state_id' => 25, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Teluk Wondama", 'state_id' => 25, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Teluk Bintuni", 'state_id' => 25, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Raja Ampat", 'state_id' => 25, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sorong Selatan", 'state_id' => 25, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Fak Fak", 'state_id' => 25, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Manokwari", 'state_id' => 25, 'created_at' => $now, 'updated_at' => $now ],
            [ 'name' => "Kab. Sorong", 'state_id' => 25, 'created_at' => $now, 'updated_at' => $now ],
        ];

        foreach ($data as $row) {
            City::firstOrCreate(['name' => $row['name']], $row);
        }
    }
}
